/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicKatasterSearchRouteImport } from './routes/api/public/kataster/search'
import { Route as ApiPublicKatasterLvRouteImport } from './routes/api/public/kataster/lv'
import { Route as ApiPublicKatasterIdentifyRouteImport } from './routes/api/public/kataster/identify'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKatasterSearchRoute = ApiPublicKatasterSearchRouteImport.update({
  id: '/api/public/kataster/search',
  path: '/api/public/kataster/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKatasterLvRoute = ApiPublicKatasterLvRouteImport.update({
  id: '/api/public/kataster/lv',
  path: '/api/public/kataster/lv',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKatasterIdentifyRoute =
  ApiPublicKatasterIdentifyRouteImport.update({
    id: '/api/public/kataster/identify',
    path: '/api/public/kataster/identify',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/api/public/kataster/identify': typeof ApiPublicKatasterIdentifyRoute
  '/api/public/kataster/lv': typeof ApiPublicKatasterLvRoute
  '/api/public/kataster/search': typeof ApiPublicKatasterSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/api/public/kataster/identify': typeof ApiPublicKatasterIdentifyRoute
  '/api/public/kataster/lv': typeof ApiPublicKatasterLvRoute
  '/api/public/kataster/search': typeof ApiPublicKatasterSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/api/public/kataster/identify': typeof ApiPublicKatasterIdentifyRoute
  '/api/public/kataster/lv': typeof ApiPublicKatasterLvRoute
  '/api/public/kataster/search': typeof ApiPublicKatasterSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/api/public/kataster/identify'
    | '/api/public/kataster/lv'
    | '/api/public/kataster/search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/api/public/kataster/identify'
    | '/api/public/kataster/lv'
    | '/api/public/kataster/search'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/api/public/kataster/identify'
    | '/api/public/kataster/lv'
    | '/api/public/kataster/search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  ApiPublicKatasterIdentifyRoute: typeof ApiPublicKatasterIdentifyRoute
  ApiPublicKatasterLvRoute: typeof ApiPublicKatasterLvRoute
  ApiPublicKatasterSearchRoute: typeof ApiPublicKatasterSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kataster/search': {
      id: '/api/public/kataster/search'
      path: '/api/public/kataster/search'
      fullPath: '/api/public/kataster/search'
      preLoaderRoute: typeof ApiPublicKatasterSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kataster/lv': {
      id: '/api/public/kataster/lv'
      path: '/api/public/kataster/lv'
      fullPath: '/api/public/kataster/lv'
      preLoaderRoute: typeof ApiPublicKatasterLvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kataster/identify': {
      id: '/api/public/kataster/identify'
      path: '/api/public/kataster/identify'
      fullPath: '/api/public/kataster/identify'
      preLoaderRoute: typeof ApiPublicKatasterIdentifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  ApiPublicKatasterIdentifyRoute: ApiPublicKatasterIdentifyRoute,
  ApiPublicKatasterLvRoute: ApiPublicKatasterLvRoute,
  ApiPublicKatasterSearchRoute: ApiPublicKatasterSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
