/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as ApiAuthSetupRouteImport } from './routes/api/auth/setup'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthAdminIndexRouteImport } from './routes/api/auth/admin/index'
import { Route as ApiPublicKatasterSearchRouteImport } from './routes/api/public/kataster/search'
import { Route as ApiPublicKatasterLvRouteImport } from './routes/api/public/kataster/lv'
import { Route as ApiPublicKatasterIdentifyRouteImport } from './routes/api/public/kataster/identify'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSetupRoute = ApiAuthSetupRouteImport.update({
  id: '/api/auth/setup',
  path: '/api/auth/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthAdminIndexRoute = ApiAuthAdminIndexRouteImport.update({
  id: '/api/auth/admin/',
  path: '/api/auth/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKatasterSearchRoute = ApiPublicKatasterSearchRouteImport.update({
  id: '/api/public/kataster/search',
  path: '/api/public/kataster/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKatasterLvRoute = ApiPublicKatasterLvRouteImport.update({
  id: '/api/public/kataster/lv',
  path: '/api/public/kataster/lv',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKatasterIdentifyRoute =
  ApiPublicKatasterIdentifyRouteImport.update({
    id: '/api/public/kataster/identify',
    path: '/api/public/kataster/identify',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/setup': typeof ApiAuthSetupRoute
  '/api/public/kataster/identify': typeof ApiPublicKatasterIdentifyRoute
  '/api/public/kataster/lv': typeof ApiPublicKatasterLvRoute
  '/api/public/kataster/search': typeof ApiPublicKatasterSearchRoute
  '/api/auth/admin/': typeof ApiAuthAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/setup': typeof ApiAuthSetupRoute
  '/api/public/kataster/identify': typeof ApiPublicKatasterIdentifyRoute
  '/api/public/kataster/lv': typeof ApiPublicKatasterLvRoute
  '/api/public/kataster/search': typeof ApiPublicKatasterSearchRoute
  '/api/auth/admin': typeof ApiAuthAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/setup': typeof ApiAuthSetupRoute
  '/api/public/kataster/identify': typeof ApiPublicKatasterIdentifyRoute
  '/api/public/kataster/lv': typeof ApiPublicKatasterLvRoute
  '/api/public/kataster/search': typeof ApiPublicKatasterSearchRoute
  '/api/auth/admin/': typeof ApiAuthAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin/users'
    | '/admin/'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/setup'
    | '/api/public/kataster/identify'
    | '/api/public/kataster/lv'
    | '/api/public/kataster/search'
    | '/api/auth/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/users'
    | '/admin'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/setup'
    | '/api/public/kataster/identify'
    | '/api/public/kataster/lv'
    | '/api/public/kataster/search'
    | '/api/auth/admin'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/admin/users'
    | '/admin/'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/setup'
    | '/api/public/kataster/identify'
    | '/api/public/kataster/lv'
    | '/api/public/kataster/search'
    | '/api/auth/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthSetupRoute: typeof ApiAuthSetupRoute
  ApiPublicKatasterIdentifyRoute: typeof ApiPublicKatasterIdentifyRoute
  ApiPublicKatasterLvRoute: typeof ApiPublicKatasterLvRoute
  ApiPublicKatasterSearchRoute: typeof ApiPublicKatasterSearchRoute
  ApiAuthAdminIndexRoute: typeof ApiAuthAdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/setup': {
      id: '/api/auth/setup'
      path: '/api/auth/setup'
      fullPath: '/api/auth/setup'
      preLoaderRoute: typeof ApiAuthSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/admin/': {
      id: '/api/auth/admin/'
      path: '/api/auth/admin'
      fullPath: '/api/auth/admin/'
      preLoaderRoute: typeof ApiAuthAdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kataster/search': {
      id: '/api/public/kataster/search'
      path: '/api/public/kataster/search'
      fullPath: '/api/public/kataster/search'
      preLoaderRoute: typeof ApiPublicKatasterSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kataster/lv': {
      id: '/api/public/kataster/lv'
      path: '/api/public/kataster/lv'
      fullPath: '/api/public/kataster/lv'
      preLoaderRoute: typeof ApiPublicKatasterLvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kataster/identify': {
      id: '/api/public/kataster/identify'
      path: '/api/public/kataster/identify'
      fullPath: '/api/public/kataster/identify'
      preLoaderRoute: typeof ApiPublicKatasterIdentifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthSetupRoute: ApiAuthSetupRoute,
  ApiPublicKatasterIdentifyRoute: ApiPublicKatasterIdentifyRoute,
  ApiPublicKatasterLvRoute: ApiPublicKatasterLvRoute,
  ApiPublicKatasterSearchRoute: ApiPublicKatasterSearchRoute,
  ApiAuthAdminIndexRoute: ApiAuthAdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
